databases:
  - name: nomadcafe_DB
    databaseName: nomadcafe_db
    user: nomadcafe
    region: singapore

services:
  - type: web
    name: nomadcafe
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nomadcafe_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
